export {default as Header,ShowGoTop} from "./Header/Header";
export {default as LandingPage,MoveBackgroundImage} from "./LandingPage/LandingPage";
export {default as ControlMenu} from "./ControlMenu/ControlMenu";
export {default as AboutUs} from "./About US/AboutUs";
export {default as TodaySpecial,MoveSpecialBackgroundImage} from "./TodaySpecial/TodaySpecial";
export {default as OurMenu } from "./OurMenu/OurMenu";
export {default as OurTeam,MoveTeamBackground} from "./OurTeam/OurTeam";
export {default as Gallery} from "./Gallery/Gallery";
export {default as OurBlog,MoveBlogBackground} from "./OurBlog/OurBlog";
export {default as Pricing} from "./Pricing/Pricing";
export {default as Reservation } from "./Reservation/Reservation";