import image1 from "../../images/gallery_01.jpg";
import image2 from "../../images/gallery_02.jpg";
import image3 from "../../images/gallery_03.jpg";
import image4 from "../../images/gallery_04.jpg";
import image5 from "../../images/gallery_05.jpg";
import image6 from "../../images/gallery_06.jpg";
import image7 from "../../images/gallery_07.jpg";
import image8 from "../../images/gallery_08.jpg";
import image9 from "../../images/gallery_09.jpg";
import image10 from "../../images/gallery_10.jpg";
import image11 from "../../images/gallery_02.jpg";
import image12 from "../../images/gallery_01.jpg";
const Images = [image1,image2,image3,image4,image5,image6,image7,image8,image9,image10,image11,image12];
export default Images;